### ISSUE TITLE
show tabs button

### ISSUE THREAD

**Issue by feipinxiang** [JayT5/ChromePie#33] opened 2016-11-13 02:02 UTC
show tabs button doesn't work with chrome 54.（nexus6 android6.0）

**Comment by apnof** [comment] 2016-11-23 14:28
Can confirm for
Chrome 54.0.2840.85
Android 5.1.1 (Sony Z1 compact/D5503)

Maybe duplicate of https://github.com/JayT5/ChromePie/issues/28
?

**Comment by JayT5** [comment] 2016-12-11 17:43
This has been fixed here: 21ca791

**Closed by JayT5** 2016-12-11 17:43 UTC

**Comment by apnof** [comment] 2017-01-12 21:14
Can confirm: working again for
v 0.6 (2016-12-21)
Chrome 55.0.2883.91
Thanks!
